module:
  hugoVersion:
    min: "0.84.0"

params:
  ananke_socials:
  - name: twitter
    label: Twitter
    url: https://twitter.com/Vcorangechan
  - name: github
    label: Github
    url: https://github.com/vcorange-chan
  - name: youtube
    label: YouTube
    url: https://www.youtube.com/channel/UC3u31-X1TNVeY08QU1dVhDw
  - name: facebook
    label: Facebook
    follow: false
  - name: rss
    label: RSS
    url: /index.xml