baseURL = "http://vcorange-chan.github.io/"
languageCode = "en-uk"
title = "Clifford's Blog"
theme = 'ananke'
resourceDir = "../resources"


DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 6 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = true

[languages]
  [languages.en]
    title = "Clifford's space"
    weight = 1
    contentDir = "content/en"
    # languageDirection = 'rtl' for Right-To-Left languages
  [languages.zh]
    title = "维C橙的空间"
    author = "维C橙"
    weight = 2
    contentDir = "content/cn"

[sitemap]
  changefreq = "daily"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  text_color = ""
  author = "CliffordChan"
  favicon = "/images/icon/favicon-32x32.png"
  site_logo = "/images/icon/apple-touch-icon.png"
  description = "This is vcorange space. Clifford Chan's blog"
  # choose a background color from any on this page: https://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  recent_posts_number = 5
  commentoEnable = false
  from = "2023"
  math = true

  
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true